[project]
name = "lab1-sql"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "duckdb>=1.4.3",
    "pandas>=3.0.0",
    "plotly>=6.5.2",
]
